"""empty message

Revision ID: 24005ce0a560
Revises: 2b351a381ee3
Create Date: 2026-03-12 15:07:24.298776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24005ce0a560'
down_revision: Union[str, None] = '2b351a381ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items_sold', sa.Column('purchase_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items_sold', 'purchase_price')
    # ### end Alembic commands ###
