"""renamed shop models

Revision ID: 2a4389b250ab
Revises: d048f3e7558d
Create Date: 2025-04-23 10:34:51.563245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a4389b250ab'
down_revision: Union[str, None] = 'd048f3e7558d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_access',
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('shop_id', 'user_id')
    )
    op.create_table('shop_cart',
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint('quantity > 0', name='check_quantity_positive'),
    sa.ForeignKeyConstraint(['item_id', 'shop_id'], ['items_in_shops.item_id', 'items_in_shops.shop_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('shop_id', 'user_id', 'item_id')
    )
    op.drop_table('shops_carts')
    op.drop_table('shops_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops_users',
    sa.Column('shop_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name='shops_users_shop_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='shops_users_user_id_fkey'),
    sa.PrimaryKeyConstraint('shop_id', 'user_id', name='shops_users_pkey')
    )
    op.create_table('shops_carts',
    sa.Column('shop_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.CheckConstraint('quantity > 0', name='check_quantity_positive'),
    sa.ForeignKeyConstraint(['item_id', 'shop_id'], ['items_in_shops.item_id', 'items_in_shops.shop_id'], name='shops_carts_item_id_shop_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='shops_carts_user_id_fkey'),
    sa.PrimaryKeyConstraint('shop_id', 'user_id', 'item_id', name='shops_carts_pkey')
    )
    op.drop_table('shop_cart')
    op.drop_table('shop_access')
    # ### end Alembic commands ###
