"""empty message

Revision ID: 2b351a381ee3
Revises: 310266c173f9
Create Date: 2026-03-02 11:41:59.972788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b351a381ee3'
down_revision: Union[str, None] = '310266c173f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shop_queues_item_id_shop_id_fkey', 'shop_queues', type_='foreignkey')
    op.create_foreign_key(None, 'shop_queues', 'shops', ['shop_id'], ['id'])
    op.create_foreign_key(None, 'shop_queues', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop_queues', type_='foreignkey')
    op.drop_constraint(None, 'shop_queues', type_='foreignkey')
    op.create_foreign_key('shop_queues_item_id_shop_id_fkey', 'shop_queues', 'shop_items', ['item_id', 'shop_id'], ['item_id', 'shop_id'])
    # ### end Alembic commands ###
