"""renamed item model

Revision ID: 310266c173f9
Revises: 2a4389b250ab
Create Date: 2025-04-23 11:16:12.546100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '310266c173f9'
down_revision: Union[str, None] = '2a4389b250ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_items',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Integer(), nullable=False),
    sa.CheckConstraint('price > 0', name='check_price_positive'),
    sa.CheckConstraint('quantity >= 0', name='check_quantity'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'shop_id')
    )
    op.create_table('shop_queues',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id', 'shop_id'], ['shop_items.item_id', 'shop_items.shop_id'], ),
    sa.PrimaryKeyConstraint('item_id', 'shop_id', 'created_at')
    )
    op.drop_table('items_queues')
    op.drop_constraint('shop_cart_item_id_shop_id_fkey', 'shop_cart', type_='foreignkey')
    op.create_foreign_key(None, 'shop_cart', 'shop_items', ['item_id', 'shop_id'], ['item_id', 'shop_id'])
    op.drop_table('items_in_shops')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop_cart', type_='foreignkey')
    op.create_foreign_key('shop_cart_item_id_shop_id_fkey', 'shop_cart', 'items_in_shops', ['item_id', 'shop_id'], ['item_id', 'shop_id'])
    op.create_table('items_in_shops',
    sa.Column('item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('shop_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purchase_price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('price > 0', name='check_price_positive'),
    sa.CheckConstraint('quantity >= 0', name='check_quantity'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='items_in_shops_item_id_fkey'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name='items_in_shops_shop_id_fkey'),
    sa.PrimaryKeyConstraint('item_id', 'shop_id', name='items_in_shops_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('items_queues',
    sa.Column('item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('shop_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purchase_price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id', 'shop_id'], ['items_in_shops.item_id', 'items_in_shops.shop_id'], name='items_queues_item_id_shop_id_fkey'),
    sa.PrimaryKeyConstraint('item_id', 'shop_id', 'created_at', name='items_queues_pkey')
    )
    op.drop_table('shop_queues')
    op.drop_table('shop_items')
    # ### end Alembic commands ###
