"""empty message

Revision ID: 799870b0f453
Revises: 24005ce0a560
Create Date: 2026-03-12 15:26:31.472083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '799870b0f453'
down_revision: Union[str, None] = '24005ce0a560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items_sold', sa.Column('profit', sa.BigInteger(), nullable=False))
    op.drop_column('items_sold', 'income')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items_sold', sa.Column('income', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('items_sold', 'profit')
    # ### end Alembic commands ###
